// generated by Fast Light User Interface Designer (fluid) version 1.0303

#include "test.h"

Fl_Menu_Item EMDL_viewer::menu_[] = {
 {"File", 0,  0, 0, 64, FL_NORMAL_LABEL, 0, 14, 0},
 {"item", 0,  0, 0, 0, FL_NORMAL_LABEL, 0, 14, 0},
 {0,0,0,0,0,0,0,0,0},
 {"Tools", 0,  0, 0, 64, FL_NORMAL_LABEL, 0, 14, 0},
 {0,0,0,0,0,0,0,0,0},
 {0,0,0,0,0,0,0,0,0}
};

EMDL_viewer::EMDL_viewer() {
  Fl_Double_Window* w;
  { Fl_Double_Window* o = new Fl_Double_Window(303, 243);
    w = o;
    o->user_data((void*)(this));
    { Fl_Menu_Bar* o = new Fl_Menu_Bar(0, 0, 311, 20);
      o->menu(menu_);
    } // Fl_Menu_Bar* o
    o->end();
	o->show( );
  } // Fl_Double_Window* o

}
